/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-08-20 18:03:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "my-header.html", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc\r\n");
      out.write("\t\tsit amet sem ullamcorper, eleifend felis in, tristique lorem. Aenean\r\n");
      out.write("\t\tat mi sodales, molestie eros eu, vestibulum tellus. Pellentesque justo\r\n");
      out.write("\t\tturpis, mattis eget ante ut, hendrerit sodales augue. Quisque sit amet\r\n");
      out.write("\t\tpurus a ipsum blandit suscipit. Sed finibus posuere efficitur.\r\n");
      out.write("\t\tSuspendisse potenti. Cras ut consectetur nunc. Phasellus cursus, leo\r\n");
      out.write("\t\tet luctus varius, mauris enim mollis felis, vulputate volutpat nunc\r\n");
      out.write("\t\tquam et neque. Nunc tincidunt, enim quis consectetur suscipit, sem\r\n");
      out.write("\t\telit consectetur felis, ut commodo sapien enim sed ipsum. Nunc\r\n");
      out.write("\t\tpulvinar massa et finibus eleifend. Nulla facilisi.</p>\r\n");
      out.write("\r\n");
      out.write("\t<p>Sed finibus eleifend leo convallis fringilla. Vestibulum\r\n");
      out.write("\t\tvenenatis dolor malesuada, molestie ipsum ac, ultricies ligula. Proin\r\n");
      out.write("\t\tin ligula metus. Integer facilisis quam neque, et molestie lacus\r\n");
      out.write("\t\trhoncus at. Sed id nulla massa. Pellentesque consectetur malesuada\r\n");
      out.write("\t\trisus, consequat consequat quam. Pellentesque auctor auctor arcu quis\r\n");
      out.write("\t\tefficitur. Sed pretium lobortis tellus id luctus. Vestibulum et nisi\r\n");
      out.write("\t\teget nulla consequat posuere sit amet in ipsum. Duis ac ipsum\r\n");
      out.write("\t\tfringilla, posuere purus eget, commodo augue. Class aptent taciti\r\n");
      out.write("\t\tsociosqu ad litora torquent per conubia nostra, per inceptos\r\n");
      out.write("\t\thimenaeos. Donec laoreet nibh mauris, non aliquet leo fringilla eget.\r\n");
      out.write("\t\tIn hac habitasse platea dictumst. Integer efficitur sed dui at\r\n");
      out.write("\t\tdapibus.</p>\r\n");
      out.write("\r\n");
      out.write("\t<p>Morbi id nulla elementum, viverra urna ut, pellentesque mauris.\r\n");
      out.write("\t\tPhasellus vestibulum sagittis pulvinar. Pellentesque in dolor placerat\r\n");
      out.write("\t\tnibh tempus malesuada vitae sed mauris. Curabitur eleifend erat quis\r\n");
      out.write("\t\tsapien rhoncus, et ullamcorper eros rutrum. Vivamus lacus sem, congue\r\n");
      out.write("\t\ta orci molestie, faucibus rutrum ante. Etiam hendrerit vestibulum\r\n");
      out.write("\t\tnibh, at laoreet ante convallis at. Nullam id felis vestibulum,\r\n");
      out.write("\t\taliquet sapien vitae, eleifend orci. Nunc elit nunc, ornare id erat\r\n");
      out.write("\t\tat, suscipit imperdiet eros. Sed et leo leo.</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "my-footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
